[phases.setup]
nixPkgs = ['nodejs_20', 'yarn', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = ['yarn next:build']

[start]
cmd = 'yarn next:serve'
