/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    FileRegistry: {
      address: "0xF2cb3cfA36Bfb95E0FD855C1b41Ab19c517FcDB9",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "field",
              type: "string",
            },
          ],
          name: "EmptyValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileAlreadyRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidContentHash",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "NotFileOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "FileDelisted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "FileRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldPayToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "PayToChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldPriceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "PriceChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "VisibilityChanged",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_PAGE_SIZE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PAYMENT_ASSET",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
          ],
          name: "computeFileId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "delistFile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "getFile",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getFileCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getFiles",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "ids",
              type: "bytes32[]",
            },
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem[]",
              name: "files",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "registerFile",
          outputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "setPayToAccountId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "setPrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "setVisibility",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40310047,
      hederaContractId: "0.0.10443939",
    },
    PolicyRegistry: {
      address: "0xC3549920b94a795D75E6C003944943D552C46F97",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "AlreadyResolved",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPolicyTerms",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "NotPolicyCreator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "PolicyAlreadyExists",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "PolicyNotFound",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "policyholder",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "coverageStart",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "coverageEnd",
              type: "uint256",
            },
          ],
          name: "PolicyCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "resolutionHash",
              type: "bytes32",
            },
          ],
          name: "PolicyResolved",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_PAGE_SIZE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
          ],
          name: "computePolicyId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "policyholder",
              type: "string",
            },
            {
              internalType: "string",
              name: "dataChainId",
              type: "string",
            },
            {
              internalType: "string",
              name: "stablecoinSymbol",
              type: "string",
            },
            {
              internalType: "address",
              name: "stablecoinAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "referencePoolAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "thresholdBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minimumDurationMinutes",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "payoutAmountBaseUnits",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "payoutTokenSymbol",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "coverageStart",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "coverageEnd",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxEvidenceBudgetTinybar",
              type: "uint256",
            },
          ],
          name: "createPolicy",
          outputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getPolicies",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "ids",
              type: "bytes32[]",
            },
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "policyholder",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "dataChainId",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "stablecoinSymbol",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "stablecoinAddress",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "referencePoolAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "thresholdBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "minimumDurationMinutes",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payoutAmountBaseUnits",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "payoutTokenSymbol",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "coverageStart",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "coverageEnd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxEvidenceBudgetTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "resolved",
                  type: "bool",
                },
                {
                  internalType: "bytes32",
                  name: "resolutionHash",
                  type: "bytes32",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct PolicyRegistry.Policy[]",
              name: "policies",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "getPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "policyholder",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "dataChainId",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "stablecoinSymbol",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "stablecoinAddress",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "referencePoolAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "thresholdBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "minimumDurationMinutes",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payoutAmountBaseUnits",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "payoutTokenSymbol",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "coverageStart",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "coverageEnd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxEvidenceBudgetTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "resolved",
                  type: "bool",
                },
                {
                  internalType: "bytes32",
                  name: "resolutionHash",
                  type: "bytes32",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct PolicyRegistry.Policy",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getPolicyCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "resolutionHash",
              type: "bytes32",
            },
          ],
          name: "resolvePolicy",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40310051,
      hederaContractId: "0.0.10443942",
    },
  },
  31337: {
    FileRegistry: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "field",
              type: "string",
            },
          ],
          name: "EmptyValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileAlreadyRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidContentHash",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "NotFileOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "FileDelisted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "FileRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldPayToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "PayToChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldPriceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "PriceChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "VisibilityChanged",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_PAGE_SIZE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PAYMENT_ASSET",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
          ],
          name: "computeFileId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "delistFile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "getFile",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getFileCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getFiles",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "ids",
              type: "bytes32[]",
            },
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem[]",
              name: "files",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "registerFile",
          outputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "setPayToAccountId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "setPrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "setVisibility",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    PolicyRegistry: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "AlreadyResolved",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPolicyTerms",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "NotPolicyCreator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "PolicyAlreadyExists",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "PolicyNotFound",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "policyholder",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "coverageStart",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "coverageEnd",
              type: "uint256",
            },
          ],
          name: "PolicyCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "resolutionHash",
              type: "bytes32",
            },
          ],
          name: "PolicyResolved",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_PAGE_SIZE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
          ],
          name: "computePolicyId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "policyholder",
              type: "string",
            },
            {
              internalType: "string",
              name: "dataChainId",
              type: "string",
            },
            {
              internalType: "string",
              name: "stablecoinSymbol",
              type: "string",
            },
            {
              internalType: "address",
              name: "stablecoinAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "referencePoolAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "thresholdBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minimumDurationMinutes",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "payoutAmountBaseUnits",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "payoutTokenSymbol",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "coverageStart",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "coverageEnd",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxEvidenceBudgetTinybar",
              type: "uint256",
            },
          ],
          name: "createPolicy",
          outputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getPolicies",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "ids",
              type: "bytes32[]",
            },
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "policyholder",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "dataChainId",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "stablecoinSymbol",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "stablecoinAddress",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "referencePoolAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "thresholdBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "minimumDurationMinutes",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payoutAmountBaseUnits",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "payoutTokenSymbol",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "coverageStart",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "coverageEnd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxEvidenceBudgetTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "resolved",
                  type: "bool",
                },
                {
                  internalType: "bytes32",
                  name: "resolutionHash",
                  type: "bytes32",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct PolicyRegistry.Policy[]",
              name: "policies",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "getPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "policyholder",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "dataChainId",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "stablecoinSymbol",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "stablecoinAddress",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "referencePoolAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "thresholdBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "minimumDurationMinutes",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payoutAmountBaseUnits",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "payoutTokenSymbol",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "coverageStart",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "coverageEnd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxEvidenceBudgetTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "resolved",
                  type: "bool",
                },
                {
                  internalType: "bytes32",
                  name: "resolutionHash",
                  type: "bytes32",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct PolicyRegistry.Policy",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getPolicyCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "resolutionHash",
              type: "bytes32",
            },
          ],
          name: "resolvePolicy",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
